apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4j-demo
spec:
  selector:
    matchLabels:
      run: log4j-demo
  replicas: 1
  template:
    metadata:
      labels:
        run: log4j-demo
    spec:
      containers:
        - name: log4j-demo
          image: $IMAGE
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: log4j-demo
spec:
  selector:
    run: log4j-demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080