name: Add Labels

on:
  issues:
    type: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  issue_check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{ github.event.issue.title }}" == *"bug"* ]]
          then
            curl -X POST  -H "Authorization: Token $GITHUB_TOKEN" -d '{"labels": ["bug"]}' ${{ github.event.issue.url }}/labels
          fi
